=== tillpl/anapher_annotation/masxml/dtd/masxmlpd.dtd
<!-- masxmlpd_gnome.dtd                                               -->
<!-- DTD for Minimal Anaphoric Syntax - XML for Phrase Detectives     -->
<!--      (Output)                                                    -->
<!--      v. 2.10                                                     -->
<!-- Author: Massimo Poesio                                           -->
<!--      (based on the GNOME corpus .dtd)                            -->
<!-- Created:  2004/06/29                                             -->
<!-- Modified:                                                        -->
<!--           2008/08/07 - 2.1 (adapted for Olivia converter)        -->
<!--           2008/09/03 - 2.2 (TEI-style header)                    -->
<!--           2008/10/31 - 2.4 (body)                                -->
<!--           2008/11/06 - 2.6 after running xjparse
                                added lemma and xpos to W
                                changed order of resp and name        -->
<!--           2017/01/24 - 2.9 Multiple changes to accommodate 
                                Phrase Detectives schema in v1.0      -->
<!--           2018/12/07 - 2.9 Version for GNOME                     -->


<!--   ELEMENTS 	MIN 	CONTENTS     (EXCEPTIONS)             -->

<!-- ================ GENERAL ENTITIES ============================== -->

<!ENTITY % lt       '<'>
<!ENTITY % bits     'emph'>
<!ENTITY % catvals  'a-np|another-np|q-np|num-np|meas-np|this-np|that-np|such-np|wh-np|poss-np|bare-np|pn|the-pn|the-np|pers-pro|poss-pro|refl-pro|rec-pro|q-pro|wh-pro|free-rel|this-pro|that-pro|num-ana|null-ana|coord-np|gerund|complementizer|no-cat|unsure-cat'>
<!ENTITY % pervals  'per1|per2|per3|undersp-per|no-per|unsure-per'>
<!ENTITY % numvals  'sing|plur|undersp-num|no-num|unsure-num'>
<!ENTITY % genvals  'fem|masc|neut|undersp-gen|any|no-gen|unsure-gen'>

<!-- ================ GNOMEDOC ====================================== -->

<!-- The outer element of a document of the corpus -->

<!ELEMENT gnomedoc  (header?,body)>       
<!ATTLIST gnomedoc
          id      ID      #IMPLIED>

<!-- ================ HEADERS ======================================== -->

<!-- New TEI-style header -->
<!ELEMENT header    (fileDesc,revisionDesc?)>
<!-- file description:  a full bibliographical description of the computer -->
<!-- file itself, from which a user of the text could derive a proper -->
<!-- bibliographic citation -->
<!ELEMENT fileDesc  (titleStmt,publicationStmt,sourceDesc)>
<!-- revision history:   allows the encoder to provide a history of changes -->
<!-- made during the development of the electronic text. -->
<!ELEMENT revisionDesc (change+)>
<!ELEMENT titleStmt (title,author)>
<!ELEMENT publicationStmt ((book|web|leaflet|miscsource),availability,date?)>
<!ELEMENT sourceDesc (filename,date)>
<!ELEMENT title	    (#PCDATA)>
<!ELEMENT author    (#PCDATA)>
<!ELEMENT respStmt  (name,resp)>
<!ELEMENT resp      (#PCDATA)>
<!ELEMENT name      (#PCDATA)>
<!ELEMENT book      (publisher,pubPlace,idno?)>
<!ELEMENT publisher (#PCDATA)>
<!ELEMENT pubPlace  (#PCDATA)>
<!ELEMENT date	    (#PCDATA)>
<!-- ISBN, etc. -->
<!ELEMENT idno      (#PCDATA)>
<!-- Copyright info -->
<!ELEMENT availability (#PCDATA)>
<!ELEMENT web       (publisher,url)>
<!ELEMENT url       (#PCDATA)>
<!ELEMENT leaflet   (publisher)>
<!ELEMENT miscsource  (#PCDATA)> 
<!ELEMENT filename  (#PCDATA)>
<!-- item already used -->
<!ELEMENT change    (date, respStmt, TEIitem)>
<!ELEMENT TEIitem  (#PCDATA)>

<!-- ================ LAYOUT ======================================== -->

<!ELEMENT body     (section)>

<!ELEMENT section  (title|p|s|PDante|list)+ >
<!ATTLIST section
          id      ID      #IMPLIED>
<!ELEMENT p	  (#PCDATA|ne|s|title|list|PDante|sbar|emph)* >
<!ATTLIST p
          id      ID      #IMPLIED>
<!ELEMENT s	  (#PCDATA|ne|ve|W|unit|GNOMEante|PDante|sbar)* >
<!ATTLIST s
          id      ID      #REQUIRED
          stype   (decl | int | imp | excl | unsureSTYPE )  #IMPLIED
          status  (edited|unedited)                         #IMPLIED>
<!ELEMENT unit    (#PCDATA | ne | nphead | unit | list | W | sbar | ve | emph)* >
<!ATTLIST unit
          id      ID      #IMPLIED
          subject CDATA	  #IMPLIED
          verbed  CDATA	  #IMPLIED
          finite  CDATA	  #IMPLIED
          utype   CDATA	  #IMPLIED
          >
<!ELEMENT sbar    (#PCDATA | ne | nphead | unit | list | W | sbar | ve | emph)* >
<!ATTLIST sbar
          id      ID      #IMPLIED
          >

<!ELEMENT list    (title?,(item|PDante)+)>
<!ATTLIST list 
          ltype   (normal|enum|defn|unsureLTYPE) 'unsureLTYPE'
          id	  ID	   #IMPLIED>
<!ELEMENT item    (#PCDATA|ne|unit|W|s|sbar|title|p|list|PDante)* >
<!ATTLIST item 
          id	  ID	   #IMPLIED
          term	  CDATA	   #IMPLIED>

<!-- ================ NE AND ITS ATTRIBUTES ============================ -->

<!ELEMENT ne  (W|ne|nphead|mod|ve|unit|sbar| emph)* >
<!-- here I had to remove references to parameter entities catvals, -->
<!-- pervals, numvals, and genvals because the bloody validator -->
<!-- complained -->
<!ATTLIST ne id     ID                                                  #IMPLIED
             AAcat  CDATA                                               #IMPLIED
             per    (per1|per2|per3|undersp-per|no-per|unsure-per)      #IMPLIED
             AAper  CDATA                                               #IMPLIED
             num    (sing|plur|undersp-num|no-num|unsure-num)           #IMPLIED
             AAnum  CDATA                                               #IMPLIED
             gen    (fem|masc|neut|undersp-gen|any|no-gen|unsure-gen)   #IMPLIED
             AAgen  CDATA                                               #IMPLIED 
             gf     (subj|obj|predicate|there-obj|comp|adjunct|gen|np-compl|
                     np-part|np-mod|adj-mod|no-gf| unsure-gf) 
                    "unsure-gf"
             onto   CDATA                                               #IMPLIED
             cb     CDATA                                               #IMPLIED
             lftype CDATA                                               #IMPLIED
             cat    CDATA                                               #IMPLIED
             deix   CDATA                                               #IMPLIED
             loeb   CDATA                                               #IMPLIED
             count  CDATA                                               #IMPLIED
             pnform CDATA                                               #IMPLIED
             generic CDATA                                              #IMPLIED
             den    CDATA                                               #IMPLIED
             ani    CDATA                                               #IMPLIED
             reference CDATA                                            #IMPLIED
             disc   CDATA                                               #IMPLIED
             structure CDATA                                            #IMPLIED
	     >

<!-- ================ ante AND ITS ATTRIBUTES ======================== -->
<!-- ante encodes gold annotation - straight from gnome.dtd -->
<!-- 2018/12/13 had to replace it with GNOMEante and GNOMEanchor to fix -->
<!--  compatibility with new anchor in PD -->

<!ELEMENT GNOMEante    (GNOMEanchor)+>
<!ATTLIST GNOMEante    current IDREF #REQUIRED
                  rel     (ident|element|element-inv|
                           subset|subset-inv|poss|poss-inv|
                           other|undersp-rel|unsure-rel)
                           "unsure-rel"
                  >
<!ELEMENT GNOMEanchor  EMPTY>
<!-- <!ELEMENT GNOMEanchor  (#PCDATA)> -->
<!ATTLIST GNOMEanchor  antecedent   IDREF #REQUIRED>

<!-- ================ PDante AND ITS ATTRIBUTES ======================== -->


<!ENTITY  % numjudgment '0|1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20'>
<!ELEMENT PDante  (interpretation|comment|skip)*>
<!ATTLIST PDante  id      IDREF            #REQUIRED
                  end_chr   CDATA          #IMPLIED
                  start_chr  CDATA         #IMPLIED
                  visibility   CDATA       #IMPLIED
                  >
<!ELEMENT interpretation (anchor)* >
<!ELEMENT anchor  EMPTY>
<!ATTLIST anchor  type    (DN|DO|PR|NR|SE) #REQUIRED
                  ante    CDATA            #IMPLIED
                  user_id  CDATA           #IMPLIED
                  user_rating  CDATA       #IMPLIED
                  annotation_time  CDATA   #IMPLIED
                  agree CDATA              #IMPLIED
                  mode CDATA               #IMPLIED
                  interface CDATA          #IMPLIED
                  timestamp CDATA          #IMPLIED
                  favoured CDATA           #IMPLIED
                  >
<!ELEMENT comment (#PCDATA)>
<!ATTLIST comment type_id CDATA            #IMPLIED
                  type    CDATA            #IMPLIED
                  user_rating CDATA        #IMPLIED
                  interface CDATA          #IMPLIED
                  timestamp CDATA          #IMPLIED
                  user_id  CDATA           #IMPLIED
                  >
<!ELEMENT skip    EMPTY >
<!ATTLIST skip    user_id  CDATA           #IMPLIED
                  user_rating  CDATA       #IMPLIED
                  annotation_time  CDATA   #IMPLIED
                  interface CDATA          #IMPLIED
                  timestamp CDATA          #IMPLIED
                  >



<!-- ================ NPHEAD AND ITS ATTRIBUTES ========================= -->

<!ELEMENT nphead (W | ne | unit | sbar | emph)*>
<!ATTLIST nphead id ID #IMPLIED
                 sem (pn-1st | pn-2nd | pn-1st-2nd | pn-reduced | gn-full | gn-reduced | tn | opn-full | opn-reduced | other | unsureSEM) "unsureSEM"
                 >

<!-- ================ MOD AND ITS ATTRIBUTES ============================ -->

<!ELEMENT mod (W|ne|ve|unit|sbar)*>
<!ATTLIST mod id ID #IMPLIED
              AAcat (AApre | AApost | unsureAAcat) "unsureAAcat"
              type (appos | such | poss | preadj | prenoun | postprep |
                    postpart | postnp | rel-cls | other | 
		            unsureTYPE) "unsureTYPE"
              pragm (unique | int | attr | unsurePRAGM) "unsurePRAGM"
              sem (location1 | time-period1 | possess | possinv |
                   content2 | material1 | subject7 | object3 |
                   purpose2 | identify2 | characterize1 |
                   rephrase1 | temporal-property1 | visual-property1 |
                   spatial-property1 | bodily-property1 | state4 |
                   property2 | quality1 | abstraction6 | phenomenon1 |
                   other | unsureSEM) "unsureSEM"
              coord (coord-yes | coord-no | unsureCOORD) "coord-no">

<!-- ================ VE AND ITS ATTRIBUTES ============================ -->

<!ELEMENT ve    (W+) >
<!ATTLIST ve    id     ID #IMPLIED>

<!-- ================ W   ======================== -->

<!ELEMENT W     (#PCDATA)>
<!ATTLIST W	    id	    ID	#IMPLIED
		        Lpos	CDATA	""
                Xpos	CDATA	"" 
                lemma   CDATA   "" >

<!-- ================ OTHER ELEMENTS  ======================== -->

<!ELEMENT emph  (#PCDATA)>
<!ATTLIST emph 
	  color CDATA #IMPLIED>
<!ELEMENT image (#PCDATA)>
<!ATTLIST image
          id    ID        #IMPLIED>

=== tillpl/anapher_annotation/masxml/Fatal_hilarity-game.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE gnomedoc SYSTEM "dtd/masxmlpd.dtd">
<gnomedoc>
<header>
<fileDesc>

<titleStmt>
<title>Fatal hilarity</title>
<author>Wikipedia</author></titleStmt>
<publicationStmt>
<web>
<publisher>Wikipedia</publisher>
<url>http://en.wikipedia.org/wiki/Fatal_hilarity</url></web>
<availability>All text is available under the terms of the GNU Free Documentation License</availability>
<date>3 December 2008</date></publicationStmt>
<sourceDesc>
<filename>data\game\wikipedia\unusual\Fatal_hilarity.htm</filename>
<date>3 December 2008</date></sourceDesc></fileDesc>
<revisionDesc>
<change>
<date>20 January 2022</date>
<respStmt>
<name>Juntao Yu</name>
<resp>Automatic Processing</resp>
</respStmt>
<TEIitem>Apply hidden markables and markable boundary changes</TEIitem>
</change>
<change>
<date>19 Jan 2022</date>
<respStmt>
<name>Phrase Detectives (Jon Chamberlain)</name>
<resp>Automatic Processing</resp>
</respStmt>
<TEIitem>Exported the document and annotations from the Phrase Detectives game (draft markables)</TEIitem>
</change>
<change>
<date>2009-05-08 14:27:53</date>
<respStmt>
<name>Phrase Detectives</name>
<resp>Automatic Processing</resp>
</respStmt>
<TEIitem>The document has been marked as complete (all markables are sufficiently annotated according to game criteria)</TEIitem>
</change>

<change>
<date>3 December 2008</date>
<respStmt>
<name>Mark Schellhase</name>
<resp>Automatic Processing</resp></respStmt>
<TEIitem>File converted to MASXML by automatic processing from HTML</TEIitem></change><change><date>23 April 2023</date><respStmt><name>Juntao Yu</name><resp>Automatic Processing</resp></respStmt><TEIitem>Add MPA and dali-full-anaphora-system annotations to the file.</TEIitem></change></revisionDesc>
</header>
<body>
<section>
<p id="p1">
<s id="s1">
<unit id="unit1"><ne AAcat="bare-np" AAgen="neut" AAnum="sing" AAper="per3" id="ne61200"><mod AAcat="AApre" id="AAm1"><W Lpos="JJ">Fatal</W></mod>
<nphead id="AAh1"><W Lpos="NN">hilarity</W></nphead></ne>
<ve id="ve1"><W Lpos="VBZ">refers</W></ve>
<W Lpos="TO">to</W>
<ne id="ne61201"><ne AAcat="bare-np" AAgen="neut" AAnum="sing" AAper="per3" id="ne61202"><W Lpos="NN">death</W></ne>
<ve id="ve2"><W Lpos="VBG">resulting</W></ve>
<W Lpos="IN">from</W>
<ne id="ne61203"><ne AAcat="the-np" AAgen="neut" AAnum="plur" AAper="per3" id="ne61204"><W Lpos="DT">the</W>
<mod AAcat="AApre" id="AAm2"><W Lpos="JJ">physiological</W></mod>
<W Lpos="NNS">effects</W></ne>
<W Lpos="IN">of</W>
<ne AAcat="bare-np" AAgen="neut" AAnum="sing" AAper="per3" id="ne61205"><nphead id="AAh2"><W Lpos="NN">laughter</W></nphead></ne></ne></ne>
<W Lpos=".">.</W></unit>
</s>
<PDante id="ne61200">
      <interpretation>
        <anchor agree="y" annotation_time="7" interface="0" mode="a" timestamp="2008-12-05 17:09:19" type="DN" user_id="4661c8b69624681d10ca5e0ee0a95786" user_rating="90" />
        <anchor agree="y" annotation_time="67" interface="0" mode="a" timestamp="2008-12-08 11:15:43" type="DN" user_id="15ee2757e06ae2e37323b889b40bf1e2" user_rating="100" />
        <anchor agree="y" annotation_time="70" interface="0" mode="a" timestamp="2008-12-09 16:40:23" type="DN" user_id="aee2b5ea7fdd43a086cb18b78f147727" user_rating="81" />
        <anchor agree="y" annotation_time="22" interface="0" mode="a" timestamp="2008-12-09 19:29:41" type="DN" user_id="c110584df2df3212114ad52c62d8f4f5" user_rating="90" />
        <anchor agree="y" annotation_time="7" interface="0" mode="a" timestamp="2008-12-09 21:46:43" type="DN" user_id="dcdd5016272c02bb97a138227ba7b5d6" user_rating="75" />
        <anchor agree="y" annotation_time="16" interface="0" mode="a" timestamp="2008-12-11 11:30:49" type="DN" user_id="eb1047e4a2c41644eddb434510348a28" user_rating="80" />
        <anchor agree="y" annotation_time="50" interface="0" mode="a" timestamp="2008-12-11 15:42:56" type="DN" user_id="ff8fd304f13361a6afa8ce7e945f4826" user_rating="55" />
        <anchor agree="y" annotation_time="11" interface="0" mode="a" timestamp="2008-12-11 15:57:05" type="DN" user_id="8464409b210f860769d308451450fdfe" user_rating="90" />
        <anchor agree="y" annotation_time="9" interface="0" mode="a" timestamp="2008-12-11 16:10:39" type="DN" user_id="07aab27d11d8aa01b90464e4e05773d1" user_rating="77" />
        <anchor agree="y" annotation_time="14" interface="0" mode="a" timestamp="2008-12-11 16:18:57" type="DN" user_id="73c1f07cc69e3e4211062fc8df027599" user_rating="66" />
        <anchor agree="y" annotation_time="46" interface="0" mode="a" timestamp="2009-05-08 14:21:48" type="DN" user_id="42d32752bd519da44b8d707ccdcf65dc" user_rating="75" />
        <anchor favoured="y" mode="e" timestamp="2009-03-31 12:01:09" type="DN" user_id="e2" />
        <anchor mode="e" timestamp="2009-04-15 20:27:11" type="DN" user_id="e18" />
      <anchor favoured="y" mode="e" timestamp="2023-04-25 11:50:00" type="DN" user_id="e99" /><anchor timestamp="2023-04-25 11:56:14" type="DN" user_id="MPA" /><anchor timestamp="2023-04-25 11:56:14" type="DN" user_id="dali-full-anaphora-system" /></interpretation>
    </PDante>
<PDante id="ne61201">
      <interpretation>
        <anchor agree="y" annotation_time="10" ante="ne61200" interface="0" mode="a" timestamp="2008-12-08 11:15:55" type="DO" user_id="15ee2757e06ae2e37323b889b40bf1e2" user_rating="100" />
        <anchor agree="y" annotation_time="94" ante="ne61200" interface="0" mode="a" timestamp="2008-12-11 15:58:54" type="DO" user_id="8464409b210f860769d308451450fdfe" user_rating="90" />
        <anchor agree="y" annotation_time="17" ante="ne61200" interface="0" mode="a" timestamp="2008-12-11 16:55:08" type="DO" user_id="24823915ab68b00a47d712f3967ed327" user_rating="72" />
        <anchor agree="y" annotation_time="2" ante="ne61200" interface="0" mode="a" timestamp="2008-12-11 19:05:55" type="DO" user_id="a399965d061dc0818ab4a087237c094d" user_rating="70" />
        <anchor agree="y" annotation_time="18" ante="ne61200" interface="0" mode="a" timestamp="2008-12-11 20:14:37" type="DO" user_id="00e6edca25ffe8f72efd33ca38c9584b" user_rating="92" />
        <anchor agree="y" annotation_time="12" ante="ne61200" interface="0" mode="v" timestamp="2008-12-13 12:28:45" type="DO" user_id="4b98139794ccdffa0776c49881853dcf" user_rating="69" />
        <anchor agree="y" annotation_time="10" ante="ne61200" interface="0" mode="v" timestamp="2008-12-16 16:40:37" type="DO" user_id="7022eda7a118059ed6295be780b3eee9" user_rating="57" />
        <anchor agree="y" annotation_time="4" ante="ne61200" interface="0" mode="v" timestamp="2008-12-22 11:59:57" type="DO" user_id="7022eda7a118059ed6295be780b3eee9" user_rating="57" />
        <anchor agree="y" annotation_time="8" ante="ne61200" interface="0" mode="v" timestamp="2008-12-23 13:45:22" type="DO" user_id="07770b41e1f032cfaa09012e1706e99e" user_rating="85" />
        <anchor agree="n" annotation_time="22" ante="ne61200" interface="0" mode="v" timestamp="2008-12-12 15:54:22" type="DO" user_id="1cc1fdd4fd16ea7d492c436b8adbc93c" user_rating="64" />
        <anchor ante="ne61200" mode="e" timestamp="2009-04-15 20:27:55" type="DO" user_id="e18" />
        <anchor agree="y" annotation_time="29" interface="0" mode="a" timestamp="2008-12-09 16:40:57" type="DN" user_id="aee2b5ea7fdd43a086cb18b78f147727" user_rating="81" />
        <anchor agree="y" annotation_time="5" interface="0" mode="a" timestamp="2008-12-09 19:29:50" type="DN" user_id="c110584df2df3212114ad52c62d8f4f5" user_rating="90" />
        <anchor agree="y" annotation_time="16" interface="0" mode="a" timestamp="2008-12-11 11:31:08" type="DN" user_id="eb1047e4a2c41644eddb434510348a28" user_rating="80" />
        <anchor agree="y" annotation_time="14" interface="0" mode="a" timestamp="2008-12-11 16:19:16" type="DN" user_id="73c1f07cc69e3e4211062fc8df027599" user_rating="66" />
        <anchor agree="y" annotation_time="13" interface="0" mode="a" timestamp="2008-12-14 09:37:19" type="DN" user_id="194d9de614706d298b46b549c65b489a" user_rating="90" />
        <anchor agree="y" annotation_time="5" interface="0" mode="a" timestamp="2008-12-20 22:53:09" type="DN" user_id="aee2b5ea7fdd43a086cb18b78f147727" user_rating="81" />
        <anchor agree="y" annotation_time="2" interface="0" mode="a" timestamp="2008-12-29 00:17:55" type="DN" user_id="aee2b5ea7fdd43a086cb18b78f147727" user_rating="81" />
        <anchor agree="y" annotation_time="3" interface="0" mode="a" timestamp="2008-12-29 00:22:27" type="DN" user_id="aee2b5ea7fdd43a086cb18b78f147727" user_rating="81" />
        <anchor agree="y" annotation_time="13" interface="0" mode="a" timestamp="2009-05-08 14:22:07" type="DN" user_id="42d32752bd519da44b8d707ccdcf65dc" user_rating="75" />
        <anchor agree="y" annotation_time="11" interface="0" mode="v" timestamp="2008-12-13 22:17:52" type="DN" user_id="76ed0707fdb8d0b6275edf4a2ff21fe2" user_rating="55" />
        <anchor agree="y" annotation_time="13" interface="0" mode="v" timestamp="2008-12-19 18:06:25" type="DN" user_id="f2d57b97a64ed92cd495cc2cbd22a9a5" user_rating="66" />
        <anchor agree="y" annotation_time="10" interface="0" mode="v" timestamp="2008-12-25 14:07:42" type="DN" user_id="ce6f0357565562b847acf544199cca8e" user_rating="92" />
        <anchor agree="n" annotation_time="11" interface="0" mode="v" timestamp="2008-12-11 19:05:51" type="DN" user_id="a399965d061dc0818ab4a087237c094d" user_rating="70" />
        <anchor agree="n" annotation_time="4" interface="0" mode="v" timestamp="2008-12-20 22:52:55" type="DN" user_id="aee2b5ea7fdd43a086cb18b78f147727" user_rating="81" />
        <anchor favoured="y" mode="e" timestamp="2009-04-23 12:50:53" type="DN" user_id="e2" />
        <anchor favoured="y" mode="e" timestamp="2009-04-15 20:27:55" type="DN" user_id="e18" />
        <anchor agree="y" annotation_time="19" ante="ne61200" interface="0" mode="a" timestamp="2008-12-09 21:47:05" type="PR" user_id="dcdd5016272c02bb97a138227ba7b5d6" user_rating="75" />
